# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2002877f364f4f9d11b07ca1e745c5560309e6ab47a045d164d2e38efa4829488ac512672b6ef4bea5dcc077360629f97eead356b53bcbbfb536f87cadf5d7c0

test:
  secret_key_base: 93912363107c49bb19dc6174e13dd288407c9dacc067e07b5e40c684d0e61f9a0b41abda5e58a54009874ed92320114c877aa4fa7450b2e595a7ff7d44130500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
